version: "3.9"
services:
  game-postgres:
    image: library/postgres:${POSTGRES_GAME_IMAGE_TAG:-14}
    container_name: ${POSTGRES_GAME_CONTAINER_NAME:-rating-postgres}
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRESQL_GAME_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_GAME_PASS}
      POSTGRES_DB: ${POSTGRESQL_GAME_DB}
    volumes:
      - ./db/rating:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d ${POSTGRESQL_GAME_DB} -U ${POSTGRESQL_GAME_USER}
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - ${POSTGRESQL_GAME_PORT:-5436}:5432
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak-postgres:
    image: library/postgres:${POSTGRES_KEYCLOAK_IMAGE_TAG:-14}
    container_name: ${POSTGRES_KEYCLOAK_CONTAINER_NAME:-keycloak-postgres}
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRESQL_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_KEYCLOAK_PASS}
      POSTGRES_DB: ${POSTGRESQL_KEYCLOAK_DB}
    volumes:
      - ./keycloak/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d ${POSTGRESQL_KEYCLOAK_DB} -U ${POSTGRESQL_KEYCLOAK_USER}
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - ${POSTGRESQL_KEYCLOAK_PORT:-5435}:5432
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: keycloak
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/${POSTGRESQL_KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRESQL_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_KEYCLOAK_PASS}
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - type: bind
        source: ./keycloak/import/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
        read_only: true
    ports:
      - 8282:8080
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s